// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pullrequest.proto

#ifndef PROTOBUF_pullrequest_2eproto__INCLUDED
#define PROTOBUF_pullrequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pullrequest_2eproto();
void protobuf_AssignDesc_pullrequest_2eproto();
void protobuf_ShutdownFile_pullrequest_2eproto();

class PullRequest;
class PullResponse;
class PullResponse_WorkerStat;

// ===================================================================

class PullRequest : public ::google::protobuf::Message {
 public:
  PullRequest();
  virtual ~PullRequest();

  PullRequest(const PullRequest& from);

  inline PullRequest& operator=(const PullRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PullRequest& default_instance();

  void Swap(PullRequest* other);

  // implements Message ----------------------------------------------

  PullRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PullRequest& from);
  void MergeFrom(const PullRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 toDisableWorkers = 1;
  inline int todisableworkers_size() const;
  inline void clear_todisableworkers();
  static const int kToDisableWorkersFieldNumber = 1;
  inline ::google::protobuf::int32 todisableworkers(int index) const;
  inline void set_todisableworkers(int index, ::google::protobuf::int32 value);
  inline void add_todisableworkers(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      todisableworkers() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_todisableworkers();

  // repeated int32 toRebornWorkers = 2;
  inline int torebornworkers_size() const;
  inline void clear_torebornworkers();
  static const int kToRebornWorkersFieldNumber = 2;
  inline ::google::protobuf::int32 torebornworkers(int index) const;
  inline void set_torebornworkers(int index, ::google::protobuf::int32 value);
  inline void add_torebornworkers(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      torebornworkers() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_torebornworkers();

  // required int32 useless = 3;
  inline bool has_useless() const;
  inline void clear_useless();
  static const int kUselessFieldNumber = 3;
  inline ::google::protobuf::int32 useless() const;
  inline void set_useless(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PullRequest)
 private:
  inline void set_has_useless();
  inline void clear_has_useless();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > todisableworkers_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > torebornworkers_;
  ::google::protobuf::int32 useless_;
  friend void  protobuf_AddDesc_pullrequest_2eproto();
  friend void protobuf_AssignDesc_pullrequest_2eproto();
  friend void protobuf_ShutdownFile_pullrequest_2eproto();

  void InitAsDefaultInstance();
  static PullRequest* default_instance_;
};
// -------------------------------------------------------------------

class PullResponse_WorkerStat : public ::google::protobuf::Message {
 public:
  PullResponse_WorkerStat();
  virtual ~PullResponse_WorkerStat();

  PullResponse_WorkerStat(const PullResponse_WorkerStat& from);

  inline PullResponse_WorkerStat& operator=(const PullResponse_WorkerStat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PullResponse_WorkerStat& default_instance();

  void Swap(PullResponse_WorkerStat* other);

  // implements Message ----------------------------------------------

  PullResponse_WorkerStat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PullResponse_WorkerStat& from);
  void MergeFrom(const PullResponse_WorkerStat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 tag = 1;
  inline bool has_tag() const;
  inline void clear_tag();
  static const int kTagFieldNumber = 1;
  inline ::google::protobuf::int32 tag() const;
  inline void set_tag(::google::protobuf::int32 value);

  // required int32 queueSize = 2;
  inline bool has_queuesize() const;
  inline void clear_queuesize();
  static const int kQueueSizeFieldNumber = 2;
  inline ::google::protobuf::int32 queuesize() const;
  inline void set_queuesize(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PullResponse.WorkerStat)
 private:
  inline void set_has_tag();
  inline void clear_has_tag();
  inline void set_has_queuesize();
  inline void clear_has_queuesize();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 tag_;
  ::google::protobuf::int32 queuesize_;
  friend void  protobuf_AddDesc_pullrequest_2eproto();
  friend void protobuf_AssignDesc_pullrequest_2eproto();
  friend void protobuf_ShutdownFile_pullrequest_2eproto();

  void InitAsDefaultInstance();
  static PullResponse_WorkerStat* default_instance_;
};
// -------------------------------------------------------------------

class PullResponse : public ::google::protobuf::Message {
 public:
  PullResponse();
  virtual ~PullResponse();

  PullResponse(const PullResponse& from);

  inline PullResponse& operator=(const PullResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PullResponse& default_instance();

  void Swap(PullResponse* other);

  // implements Message ----------------------------------------------

  PullResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PullResponse& from);
  void MergeFrom(const PullResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PullResponse_WorkerStat WorkerStat;

  // accessors -------------------------------------------------------

  // repeated .PullResponse.WorkerStat workers = 1;
  inline int workers_size() const;
  inline void clear_workers();
  static const int kWorkersFieldNumber = 1;
  inline const ::PullResponse_WorkerStat& workers(int index) const;
  inline ::PullResponse_WorkerStat* mutable_workers(int index);
  inline ::PullResponse_WorkerStat* add_workers();
  inline const ::google::protobuf::RepeatedPtrField< ::PullResponse_WorkerStat >&
      workers() const;
  inline ::google::protobuf::RepeatedPtrField< ::PullResponse_WorkerStat >*
      mutable_workers();

  // repeated int32 toKillWorkers = 2;
  inline int tokillworkers_size() const;
  inline void clear_tokillworkers();
  static const int kToKillWorkersFieldNumber = 2;
  inline ::google::protobuf::int32 tokillworkers(int index) const;
  inline void set_tokillworkers(int index, ::google::protobuf::int32 value);
  inline void add_tokillworkers(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      tokillworkers() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_tokillworkers();

  // required int32 useless = 3;
  inline bool has_useless() const;
  inline void clear_useless();
  static const int kUselessFieldNumber = 3;
  inline ::google::protobuf::int32 useless() const;
  inline void set_useless(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PullResponse)
 private:
  inline void set_has_useless();
  inline void clear_has_useless();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::PullResponse_WorkerStat > workers_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > tokillworkers_;
  ::google::protobuf::int32 useless_;
  friend void  protobuf_AddDesc_pullrequest_2eproto();
  friend void protobuf_AssignDesc_pullrequest_2eproto();
  friend void protobuf_ShutdownFile_pullrequest_2eproto();

  void InitAsDefaultInstance();
  static PullResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// PullRequest

// repeated int32 toDisableWorkers = 1;
inline int PullRequest::todisableworkers_size() const {
  return todisableworkers_.size();
}
inline void PullRequest::clear_todisableworkers() {
  todisableworkers_.Clear();
}
inline ::google::protobuf::int32 PullRequest::todisableworkers(int index) const {
  // @@protoc_insertion_point(field_get:PullRequest.toDisableWorkers)
  return todisableworkers_.Get(index);
}
inline void PullRequest::set_todisableworkers(int index, ::google::protobuf::int32 value) {
  todisableworkers_.Set(index, value);
  // @@protoc_insertion_point(field_set:PullRequest.toDisableWorkers)
}
inline void PullRequest::add_todisableworkers(::google::protobuf::int32 value) {
  todisableworkers_.Add(value);
  // @@protoc_insertion_point(field_add:PullRequest.toDisableWorkers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PullRequest::todisableworkers() const {
  // @@protoc_insertion_point(field_list:PullRequest.toDisableWorkers)
  return todisableworkers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PullRequest::mutable_todisableworkers() {
  // @@protoc_insertion_point(field_mutable_list:PullRequest.toDisableWorkers)
  return &todisableworkers_;
}

// repeated int32 toRebornWorkers = 2;
inline int PullRequest::torebornworkers_size() const {
  return torebornworkers_.size();
}
inline void PullRequest::clear_torebornworkers() {
  torebornworkers_.Clear();
}
inline ::google::protobuf::int32 PullRequest::torebornworkers(int index) const {
  // @@protoc_insertion_point(field_get:PullRequest.toRebornWorkers)
  return torebornworkers_.Get(index);
}
inline void PullRequest::set_torebornworkers(int index, ::google::protobuf::int32 value) {
  torebornworkers_.Set(index, value);
  // @@protoc_insertion_point(field_set:PullRequest.toRebornWorkers)
}
inline void PullRequest::add_torebornworkers(::google::protobuf::int32 value) {
  torebornworkers_.Add(value);
  // @@protoc_insertion_point(field_add:PullRequest.toRebornWorkers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PullRequest::torebornworkers() const {
  // @@protoc_insertion_point(field_list:PullRequest.toRebornWorkers)
  return torebornworkers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PullRequest::mutable_torebornworkers() {
  // @@protoc_insertion_point(field_mutable_list:PullRequest.toRebornWorkers)
  return &torebornworkers_;
}

// required int32 useless = 3;
inline bool PullRequest::has_useless() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PullRequest::set_has_useless() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PullRequest::clear_has_useless() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PullRequest::clear_useless() {
  useless_ = 0;
  clear_has_useless();
}
inline ::google::protobuf::int32 PullRequest::useless() const {
  // @@protoc_insertion_point(field_get:PullRequest.useless)
  return useless_;
}
inline void PullRequest::set_useless(::google::protobuf::int32 value) {
  set_has_useless();
  useless_ = value;
  // @@protoc_insertion_point(field_set:PullRequest.useless)
}

// -------------------------------------------------------------------

// PullResponse_WorkerStat

// required int32 tag = 1;
inline bool PullResponse_WorkerStat::has_tag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PullResponse_WorkerStat::set_has_tag() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PullResponse_WorkerStat::clear_has_tag() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PullResponse_WorkerStat::clear_tag() {
  tag_ = 0;
  clear_has_tag();
}
inline ::google::protobuf::int32 PullResponse_WorkerStat::tag() const {
  // @@protoc_insertion_point(field_get:PullResponse.WorkerStat.tag)
  return tag_;
}
inline void PullResponse_WorkerStat::set_tag(::google::protobuf::int32 value) {
  set_has_tag();
  tag_ = value;
  // @@protoc_insertion_point(field_set:PullResponse.WorkerStat.tag)
}

// required int32 queueSize = 2;
inline bool PullResponse_WorkerStat::has_queuesize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PullResponse_WorkerStat::set_has_queuesize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PullResponse_WorkerStat::clear_has_queuesize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PullResponse_WorkerStat::clear_queuesize() {
  queuesize_ = 0;
  clear_has_queuesize();
}
inline ::google::protobuf::int32 PullResponse_WorkerStat::queuesize() const {
  // @@protoc_insertion_point(field_get:PullResponse.WorkerStat.queueSize)
  return queuesize_;
}
inline void PullResponse_WorkerStat::set_queuesize(::google::protobuf::int32 value) {
  set_has_queuesize();
  queuesize_ = value;
  // @@protoc_insertion_point(field_set:PullResponse.WorkerStat.queueSize)
}

// -------------------------------------------------------------------

// PullResponse

// repeated .PullResponse.WorkerStat workers = 1;
inline int PullResponse::workers_size() const {
  return workers_.size();
}
inline void PullResponse::clear_workers() {
  workers_.Clear();
}
inline const ::PullResponse_WorkerStat& PullResponse::workers(int index) const {
  // @@protoc_insertion_point(field_get:PullResponse.workers)
  return workers_.Get(index);
}
inline ::PullResponse_WorkerStat* PullResponse::mutable_workers(int index) {
  // @@protoc_insertion_point(field_mutable:PullResponse.workers)
  return workers_.Mutable(index);
}
inline ::PullResponse_WorkerStat* PullResponse::add_workers() {
  // @@protoc_insertion_point(field_add:PullResponse.workers)
  return workers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PullResponse_WorkerStat >&
PullResponse::workers() const {
  // @@protoc_insertion_point(field_list:PullResponse.workers)
  return workers_;
}
inline ::google::protobuf::RepeatedPtrField< ::PullResponse_WorkerStat >*
PullResponse::mutable_workers() {
  // @@protoc_insertion_point(field_mutable_list:PullResponse.workers)
  return &workers_;
}

// repeated int32 toKillWorkers = 2;
inline int PullResponse::tokillworkers_size() const {
  return tokillworkers_.size();
}
inline void PullResponse::clear_tokillworkers() {
  tokillworkers_.Clear();
}
inline ::google::protobuf::int32 PullResponse::tokillworkers(int index) const {
  // @@protoc_insertion_point(field_get:PullResponse.toKillWorkers)
  return tokillworkers_.Get(index);
}
inline void PullResponse::set_tokillworkers(int index, ::google::protobuf::int32 value) {
  tokillworkers_.Set(index, value);
  // @@protoc_insertion_point(field_set:PullResponse.toKillWorkers)
}
inline void PullResponse::add_tokillworkers(::google::protobuf::int32 value) {
  tokillworkers_.Add(value);
  // @@protoc_insertion_point(field_add:PullResponse.toKillWorkers)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PullResponse::tokillworkers() const {
  // @@protoc_insertion_point(field_list:PullResponse.toKillWorkers)
  return tokillworkers_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PullResponse::mutable_tokillworkers() {
  // @@protoc_insertion_point(field_mutable_list:PullResponse.toKillWorkers)
  return &tokillworkers_;
}

// required int32 useless = 3;
inline bool PullResponse::has_useless() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PullResponse::set_has_useless() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PullResponse::clear_has_useless() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PullResponse::clear_useless() {
  useless_ = 0;
  clear_has_useless();
}
inline ::google::protobuf::int32 PullResponse::useless() const {
  // @@protoc_insertion_point(field_get:PullResponse.useless)
  return useless_;
}
inline void PullResponse::set_useless(::google::protobuf::int32 value) {
  set_has_useless();
  useless_ = value;
  // @@protoc_insertion_point(field_set:PullResponse.useless)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pullrequest_2eproto__INCLUDED
