// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pullrequest.proto

public class AutoScalerRequest {
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PullRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PullRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 toDisableWorkers = 1;</code>
     */
    java.util.List<java.lang.Integer> getToDisableWorkersList();
    /**
     * <code>repeated int32 toDisableWorkers = 1;</code>
     */
    int getToDisableWorkersCount();
    /**
     * <code>repeated int32 toDisableWorkers = 1;</code>
     */
    int getToDisableWorkers(int index);

    /**
     * <code>repeated int32 toRebornWorkers = 2;</code>
     */
    java.util.List<java.lang.Integer> getToRebornWorkersList();
    /**
     * <code>repeated int32 toRebornWorkers = 2;</code>
     */
    int getToRebornWorkersCount();
    /**
     * <code>repeated int32 toRebornWorkers = 2;</code>
     */
    int getToRebornWorkers(int index);

    /**
     * <code>required int32 useless = 3;</code>
     */
    boolean hasUseless();
    /**
     * <code>required int32 useless = 3;</code>
     */
    int getUseless();
  }
  /**
   * Protobuf type {@code PullRequest}
   */
  public static final class PullRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PullRequest)
      PullRequestOrBuilder {
    // Use PullRequest.newBuilder() to construct.
    private PullRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PullRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PullRequest defaultInstance;
    public static PullRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PullRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PullRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                toDisableWorkers_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              toDisableWorkers_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                toDisableWorkers_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                toDisableWorkers_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                toRebornWorkers_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              toRebornWorkers_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                toRebornWorkers_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                toRebornWorkers_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              useless_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          toDisableWorkers_ = java.util.Collections.unmodifiableList(toDisableWorkers_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          toRebornWorkers_ = java.util.Collections.unmodifiableList(toRebornWorkers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AutoScalerRequest.internal_static_PullRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AutoScalerRequest.internal_static_PullRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AutoScalerRequest.PullRequest.class, AutoScalerRequest.PullRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PullRequest> PARSER =
        new com.google.protobuf.AbstractParser<PullRequest>() {
      public PullRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PullRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TODISABLEWORKERS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> toDisableWorkers_;
    /**
     * <code>repeated int32 toDisableWorkers = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getToDisableWorkersList() {
      return toDisableWorkers_;
    }
    /**
     * <code>repeated int32 toDisableWorkers = 1;</code>
     */
    public int getToDisableWorkersCount() {
      return toDisableWorkers_.size();
    }
    /**
     * <code>repeated int32 toDisableWorkers = 1;</code>
     */
    public int getToDisableWorkers(int index) {
      return toDisableWorkers_.get(index);
    }

    public static final int TOREBORNWORKERS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> toRebornWorkers_;
    /**
     * <code>repeated int32 toRebornWorkers = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getToRebornWorkersList() {
      return toRebornWorkers_;
    }
    /**
     * <code>repeated int32 toRebornWorkers = 2;</code>
     */
    public int getToRebornWorkersCount() {
      return toRebornWorkers_.size();
    }
    /**
     * <code>repeated int32 toRebornWorkers = 2;</code>
     */
    public int getToRebornWorkers(int index) {
      return toRebornWorkers_.get(index);
    }

    public static final int USELESS_FIELD_NUMBER = 3;
    private int useless_;
    /**
     * <code>required int32 useless = 3;</code>
     */
    public boolean hasUseless() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 useless = 3;</code>
     */
    public int getUseless() {
      return useless_;
    }

    private void initFields() {
      toDisableWorkers_ = java.util.Collections.emptyList();
      toRebornWorkers_ = java.util.Collections.emptyList();
      useless_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUseless()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < toDisableWorkers_.size(); i++) {
        output.writeInt32(1, toDisableWorkers_.get(i));
      }
      for (int i = 0; i < toRebornWorkers_.size(); i++) {
        output.writeInt32(2, toRebornWorkers_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(3, useless_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < toDisableWorkers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(toDisableWorkers_.get(i));
        }
        size += dataSize;
        size += 1 * getToDisableWorkersList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < toRebornWorkers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(toRebornWorkers_.get(i));
        }
        size += dataSize;
        size += 1 * getToRebornWorkersList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, useless_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AutoScalerRequest.PullRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AutoScalerRequest.PullRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AutoScalerRequest.PullRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AutoScalerRequest.PullRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AutoScalerRequest.PullRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AutoScalerRequest.PullRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AutoScalerRequest.PullRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AutoScalerRequest.PullRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AutoScalerRequest.PullRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AutoScalerRequest.PullRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AutoScalerRequest.PullRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PullRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PullRequest)
        AutoScalerRequest.PullRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AutoScalerRequest.internal_static_PullRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AutoScalerRequest.internal_static_PullRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AutoScalerRequest.PullRequest.class, AutoScalerRequest.PullRequest.Builder.class);
      }

      // Construct using AutoScalerRequest.PullRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        toDisableWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        toRebornWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        useless_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AutoScalerRequest.internal_static_PullRequest_descriptor;
      }

      public AutoScalerRequest.PullRequest getDefaultInstanceForType() {
        return AutoScalerRequest.PullRequest.getDefaultInstance();
      }

      public AutoScalerRequest.PullRequest build() {
        AutoScalerRequest.PullRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AutoScalerRequest.PullRequest buildPartial() {
        AutoScalerRequest.PullRequest result = new AutoScalerRequest.PullRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          toDisableWorkers_ = java.util.Collections.unmodifiableList(toDisableWorkers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.toDisableWorkers_ = toDisableWorkers_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          toRebornWorkers_ = java.util.Collections.unmodifiableList(toRebornWorkers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.toRebornWorkers_ = toRebornWorkers_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.useless_ = useless_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AutoScalerRequest.PullRequest) {
          return mergeFrom((AutoScalerRequest.PullRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AutoScalerRequest.PullRequest other) {
        if (other == AutoScalerRequest.PullRequest.getDefaultInstance()) return this;
        if (!other.toDisableWorkers_.isEmpty()) {
          if (toDisableWorkers_.isEmpty()) {
            toDisableWorkers_ = other.toDisableWorkers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToDisableWorkersIsMutable();
            toDisableWorkers_.addAll(other.toDisableWorkers_);
          }
          onChanged();
        }
        if (!other.toRebornWorkers_.isEmpty()) {
          if (toRebornWorkers_.isEmpty()) {
            toRebornWorkers_ = other.toRebornWorkers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureToRebornWorkersIsMutable();
            toRebornWorkers_.addAll(other.toRebornWorkers_);
          }
          onChanged();
        }
        if (other.hasUseless()) {
          setUseless(other.getUseless());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUseless()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AutoScalerRequest.PullRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AutoScalerRequest.PullRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> toDisableWorkers_ = java.util.Collections.emptyList();
      private void ensureToDisableWorkersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          toDisableWorkers_ = new java.util.ArrayList<java.lang.Integer>(toDisableWorkers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getToDisableWorkersList() {
        return java.util.Collections.unmodifiableList(toDisableWorkers_);
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public int getToDisableWorkersCount() {
        return toDisableWorkers_.size();
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public int getToDisableWorkers(int index) {
        return toDisableWorkers_.get(index);
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public Builder setToDisableWorkers(
          int index, int value) {
        ensureToDisableWorkersIsMutable();
        toDisableWorkers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public Builder addToDisableWorkers(int value) {
        ensureToDisableWorkersIsMutable();
        toDisableWorkers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public Builder addAllToDisableWorkers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToDisableWorkersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toDisableWorkers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toDisableWorkers = 1;</code>
       */
      public Builder clearToDisableWorkers() {
        toDisableWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> toRebornWorkers_ = java.util.Collections.emptyList();
      private void ensureToRebornWorkersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          toRebornWorkers_ = new java.util.ArrayList<java.lang.Integer>(toRebornWorkers_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getToRebornWorkersList() {
        return java.util.Collections.unmodifiableList(toRebornWorkers_);
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public int getToRebornWorkersCount() {
        return toRebornWorkers_.size();
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public int getToRebornWorkers(int index) {
        return toRebornWorkers_.get(index);
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public Builder setToRebornWorkers(
          int index, int value) {
        ensureToRebornWorkersIsMutable();
        toRebornWorkers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public Builder addToRebornWorkers(int value) {
        ensureToRebornWorkersIsMutable();
        toRebornWorkers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public Builder addAllToRebornWorkers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToRebornWorkersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toRebornWorkers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toRebornWorkers = 2;</code>
       */
      public Builder clearToRebornWorkers() {
        toRebornWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int useless_ ;
      /**
       * <code>required int32 useless = 3;</code>
       */
      public boolean hasUseless() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 useless = 3;</code>
       */
      public int getUseless() {
        return useless_;
      }
      /**
       * <code>required int32 useless = 3;</code>
       */
      public Builder setUseless(int value) {
        bitField0_ |= 0x00000004;
        useless_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 useless = 3;</code>
       */
      public Builder clearUseless() {
        bitField0_ = (bitField0_ & ~0x00000004);
        useless_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PullRequest)
    }

    static {
      defaultInstance = new PullRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PullRequest)
  }

  public interface PullResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PullResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    java.util.List<AutoScalerRequest.PullResponse.WorkerStat> 
        getWorkersList();
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    AutoScalerRequest.PullResponse.WorkerStat getWorkers(int index);
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    int getWorkersCount();
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    java.util.List<? extends AutoScalerRequest.PullResponse.WorkerStatOrBuilder> 
        getWorkersOrBuilderList();
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    AutoScalerRequest.PullResponse.WorkerStatOrBuilder getWorkersOrBuilder(
        int index);

    /**
     * <code>repeated int32 toKillWorkers = 2;</code>
     */
    java.util.List<java.lang.Integer> getToKillWorkersList();
    /**
     * <code>repeated int32 toKillWorkers = 2;</code>
     */
    int getToKillWorkersCount();
    /**
     * <code>repeated int32 toKillWorkers = 2;</code>
     */
    int getToKillWorkers(int index);

    /**
     * <code>required int32 useless = 3;</code>
     */
    boolean hasUseless();
    /**
     * <code>required int32 useless = 3;</code>
     */
    int getUseless();
  }
  /**
   * Protobuf type {@code PullResponse}
   */
  public static final class PullResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PullResponse)
      PullResponseOrBuilder {
    // Use PullResponse.newBuilder() to construct.
    private PullResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PullResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PullResponse defaultInstance;
    public static PullResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PullResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PullResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                workers_ = new java.util.ArrayList<AutoScalerRequest.PullResponse.WorkerStat>();
                mutable_bitField0_ |= 0x00000001;
              }
              workers_.add(input.readMessage(AutoScalerRequest.PullResponse.WorkerStat.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                toKillWorkers_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              toKillWorkers_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                toKillWorkers_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                toKillWorkers_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              useless_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          workers_ = java.util.Collections.unmodifiableList(workers_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          toKillWorkers_ = java.util.Collections.unmodifiableList(toKillWorkers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AutoScalerRequest.internal_static_PullResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AutoScalerRequest.internal_static_PullResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AutoScalerRequest.PullResponse.class, AutoScalerRequest.PullResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<PullResponse> PARSER =
        new com.google.protobuf.AbstractParser<PullResponse>() {
      public PullResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PullResponse> getParserForType() {
      return PARSER;
    }

    public interface WorkerStatOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PullResponse.WorkerStat)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 tag = 1;</code>
       */
      boolean hasTag();
      /**
       * <code>required int32 tag = 1;</code>
       */
      int getTag();

      /**
       * <code>required int32 queueSize = 2;</code>
       */
      boolean hasQueueSize();
      /**
       * <code>required int32 queueSize = 2;</code>
       */
      int getQueueSize();
    }
    /**
     * Protobuf type {@code PullResponse.WorkerStat}
     */
    public static final class WorkerStat extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:PullResponse.WorkerStat)
        WorkerStatOrBuilder {
      // Use WorkerStat.newBuilder() to construct.
      private WorkerStat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private WorkerStat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final WorkerStat defaultInstance;
      public static WorkerStat getDefaultInstance() {
        return defaultInstance;
      }

      public WorkerStat getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private WorkerStat(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                tag_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                queueSize_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AutoScalerRequest.internal_static_PullResponse_WorkerStat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AutoScalerRequest.internal_static_PullResponse_WorkerStat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AutoScalerRequest.PullResponse.WorkerStat.class, AutoScalerRequest.PullResponse.WorkerStat.Builder.class);
      }

      public static com.google.protobuf.Parser<WorkerStat> PARSER =
          new com.google.protobuf.AbstractParser<WorkerStat>() {
        public WorkerStat parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new WorkerStat(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<WorkerStat> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TAG_FIELD_NUMBER = 1;
      private int tag_;
      /**
       * <code>required int32 tag = 1;</code>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 tag = 1;</code>
       */
      public int getTag() {
        return tag_;
      }

      public static final int QUEUESIZE_FIELD_NUMBER = 2;
      private int queueSize_;
      /**
       * <code>required int32 queueSize = 2;</code>
       */
      public boolean hasQueueSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 queueSize = 2;</code>
       */
      public int getQueueSize() {
        return queueSize_;
      }

      private void initFields() {
        tag_ = 0;
        queueSize_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasTag()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasQueueSize()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, tag_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, queueSize_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, tag_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, queueSize_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static AutoScalerRequest.PullResponse.WorkerStat parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(AutoScalerRequest.PullResponse.WorkerStat prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PullResponse.WorkerStat}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PullResponse.WorkerStat)
          AutoScalerRequest.PullResponse.WorkerStatOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return AutoScalerRequest.internal_static_PullResponse_WorkerStat_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return AutoScalerRequest.internal_static_PullResponse_WorkerStat_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  AutoScalerRequest.PullResponse.WorkerStat.class, AutoScalerRequest.PullResponse.WorkerStat.Builder.class);
        }

        // Construct using AutoScalerRequest.PullResponse.WorkerStat.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          tag_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          queueSize_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return AutoScalerRequest.internal_static_PullResponse_WorkerStat_descriptor;
        }

        public AutoScalerRequest.PullResponse.WorkerStat getDefaultInstanceForType() {
          return AutoScalerRequest.PullResponse.WorkerStat.getDefaultInstance();
        }

        public AutoScalerRequest.PullResponse.WorkerStat build() {
          AutoScalerRequest.PullResponse.WorkerStat result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public AutoScalerRequest.PullResponse.WorkerStat buildPartial() {
          AutoScalerRequest.PullResponse.WorkerStat result = new AutoScalerRequest.PullResponse.WorkerStat(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.tag_ = tag_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.queueSize_ = queueSize_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof AutoScalerRequest.PullResponse.WorkerStat) {
            return mergeFrom((AutoScalerRequest.PullResponse.WorkerStat)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(AutoScalerRequest.PullResponse.WorkerStat other) {
          if (other == AutoScalerRequest.PullResponse.WorkerStat.getDefaultInstance()) return this;
          if (other.hasTag()) {
            setTag(other.getTag());
          }
          if (other.hasQueueSize()) {
            setQueueSize(other.getQueueSize());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasTag()) {
            
            return false;
          }
          if (!hasQueueSize()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          AutoScalerRequest.PullResponse.WorkerStat parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (AutoScalerRequest.PullResponse.WorkerStat) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int tag_ ;
        /**
         * <code>required int32 tag = 1;</code>
         */
        public boolean hasTag() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 tag = 1;</code>
         */
        public int getTag() {
          return tag_;
        }
        /**
         * <code>required int32 tag = 1;</code>
         */
        public Builder setTag(int value) {
          bitField0_ |= 0x00000001;
          tag_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 tag = 1;</code>
         */
        public Builder clearTag() {
          bitField0_ = (bitField0_ & ~0x00000001);
          tag_ = 0;
          onChanged();
          return this;
        }

        private int queueSize_ ;
        /**
         * <code>required int32 queueSize = 2;</code>
         */
        public boolean hasQueueSize() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 queueSize = 2;</code>
         */
        public int getQueueSize() {
          return queueSize_;
        }
        /**
         * <code>required int32 queueSize = 2;</code>
         */
        public Builder setQueueSize(int value) {
          bitField0_ |= 0x00000002;
          queueSize_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 queueSize = 2;</code>
         */
        public Builder clearQueueSize() {
          bitField0_ = (bitField0_ & ~0x00000002);
          queueSize_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:PullResponse.WorkerStat)
      }

      static {
        defaultInstance = new WorkerStat(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:PullResponse.WorkerStat)
    }

    private int bitField0_;
    public static final int WORKERS_FIELD_NUMBER = 1;
    private java.util.List<AutoScalerRequest.PullResponse.WorkerStat> workers_;
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    public java.util.List<AutoScalerRequest.PullResponse.WorkerStat> getWorkersList() {
      return workers_;
    }
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    public java.util.List<? extends AutoScalerRequest.PullResponse.WorkerStatOrBuilder> 
        getWorkersOrBuilderList() {
      return workers_;
    }
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    public int getWorkersCount() {
      return workers_.size();
    }
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    public AutoScalerRequest.PullResponse.WorkerStat getWorkers(int index) {
      return workers_.get(index);
    }
    /**
     * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
     */
    public AutoScalerRequest.PullResponse.WorkerStatOrBuilder getWorkersOrBuilder(
        int index) {
      return workers_.get(index);
    }

    public static final int TOKILLWORKERS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> toKillWorkers_;
    /**
     * <code>repeated int32 toKillWorkers = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getToKillWorkersList() {
      return toKillWorkers_;
    }
    /**
     * <code>repeated int32 toKillWorkers = 2;</code>
     */
    public int getToKillWorkersCount() {
      return toKillWorkers_.size();
    }
    /**
     * <code>repeated int32 toKillWorkers = 2;</code>
     */
    public int getToKillWorkers(int index) {
      return toKillWorkers_.get(index);
    }

    public static final int USELESS_FIELD_NUMBER = 3;
    private int useless_;
    /**
     * <code>required int32 useless = 3;</code>
     */
    public boolean hasUseless() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 useless = 3;</code>
     */
    public int getUseless() {
      return useless_;
    }

    private void initFields() {
      workers_ = java.util.Collections.emptyList();
      toKillWorkers_ = java.util.Collections.emptyList();
      useless_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUseless()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getWorkersCount(); i++) {
        if (!getWorkers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < workers_.size(); i++) {
        output.writeMessage(1, workers_.get(i));
      }
      for (int i = 0; i < toKillWorkers_.size(); i++) {
        output.writeInt32(2, toKillWorkers_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(3, useless_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < workers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, workers_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < toKillWorkers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(toKillWorkers_.get(i));
        }
        size += dataSize;
        size += 1 * getToKillWorkersList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, useless_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AutoScalerRequest.PullResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AutoScalerRequest.PullResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AutoScalerRequest.PullResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AutoScalerRequest.PullResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AutoScalerRequest.PullResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AutoScalerRequest.PullResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AutoScalerRequest.PullResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AutoScalerRequest.PullResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AutoScalerRequest.PullResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AutoScalerRequest.PullResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AutoScalerRequest.PullResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PullResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PullResponse)
        AutoScalerRequest.PullResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AutoScalerRequest.internal_static_PullResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AutoScalerRequest.internal_static_PullResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AutoScalerRequest.PullResponse.class, AutoScalerRequest.PullResponse.Builder.class);
      }

      // Construct using AutoScalerRequest.PullResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWorkersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (workersBuilder_ == null) {
          workers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          workersBuilder_.clear();
        }
        toKillWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        useless_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AutoScalerRequest.internal_static_PullResponse_descriptor;
      }

      public AutoScalerRequest.PullResponse getDefaultInstanceForType() {
        return AutoScalerRequest.PullResponse.getDefaultInstance();
      }

      public AutoScalerRequest.PullResponse build() {
        AutoScalerRequest.PullResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AutoScalerRequest.PullResponse buildPartial() {
        AutoScalerRequest.PullResponse result = new AutoScalerRequest.PullResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (workersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            workers_ = java.util.Collections.unmodifiableList(workers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.workers_ = workers_;
        } else {
          result.workers_ = workersBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          toKillWorkers_ = java.util.Collections.unmodifiableList(toKillWorkers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.toKillWorkers_ = toKillWorkers_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.useless_ = useless_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AutoScalerRequest.PullResponse) {
          return mergeFrom((AutoScalerRequest.PullResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AutoScalerRequest.PullResponse other) {
        if (other == AutoScalerRequest.PullResponse.getDefaultInstance()) return this;
        if (workersBuilder_ == null) {
          if (!other.workers_.isEmpty()) {
            if (workers_.isEmpty()) {
              workers_ = other.workers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWorkersIsMutable();
              workers_.addAll(other.workers_);
            }
            onChanged();
          }
        } else {
          if (!other.workers_.isEmpty()) {
            if (workersBuilder_.isEmpty()) {
              workersBuilder_.dispose();
              workersBuilder_ = null;
              workers_ = other.workers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              workersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWorkersFieldBuilder() : null;
            } else {
              workersBuilder_.addAllMessages(other.workers_);
            }
          }
        }
        if (!other.toKillWorkers_.isEmpty()) {
          if (toKillWorkers_.isEmpty()) {
            toKillWorkers_ = other.toKillWorkers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureToKillWorkersIsMutable();
            toKillWorkers_.addAll(other.toKillWorkers_);
          }
          onChanged();
        }
        if (other.hasUseless()) {
          setUseless(other.getUseless());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUseless()) {
          
          return false;
        }
        for (int i = 0; i < getWorkersCount(); i++) {
          if (!getWorkers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AutoScalerRequest.PullResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AutoScalerRequest.PullResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AutoScalerRequest.PullResponse.WorkerStat> workers_ =
        java.util.Collections.emptyList();
      private void ensureWorkersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          workers_ = new java.util.ArrayList<AutoScalerRequest.PullResponse.WorkerStat>(workers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          AutoScalerRequest.PullResponse.WorkerStat, AutoScalerRequest.PullResponse.WorkerStat.Builder, AutoScalerRequest.PullResponse.WorkerStatOrBuilder> workersBuilder_;

      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public java.util.List<AutoScalerRequest.PullResponse.WorkerStat> getWorkersList() {
        if (workersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(workers_);
        } else {
          return workersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public int getWorkersCount() {
        if (workersBuilder_ == null) {
          return workers_.size();
        } else {
          return workersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public AutoScalerRequest.PullResponse.WorkerStat getWorkers(int index) {
        if (workersBuilder_ == null) {
          return workers_.get(index);
        } else {
          return workersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder setWorkers(
          int index, AutoScalerRequest.PullResponse.WorkerStat value) {
        if (workersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkersIsMutable();
          workers_.set(index, value);
          onChanged();
        } else {
          workersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder setWorkers(
          int index, AutoScalerRequest.PullResponse.WorkerStat.Builder builderForValue) {
        if (workersBuilder_ == null) {
          ensureWorkersIsMutable();
          workers_.set(index, builderForValue.build());
          onChanged();
        } else {
          workersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder addWorkers(AutoScalerRequest.PullResponse.WorkerStat value) {
        if (workersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkersIsMutable();
          workers_.add(value);
          onChanged();
        } else {
          workersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder addWorkers(
          int index, AutoScalerRequest.PullResponse.WorkerStat value) {
        if (workersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkersIsMutable();
          workers_.add(index, value);
          onChanged();
        } else {
          workersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder addWorkers(
          AutoScalerRequest.PullResponse.WorkerStat.Builder builderForValue) {
        if (workersBuilder_ == null) {
          ensureWorkersIsMutable();
          workers_.add(builderForValue.build());
          onChanged();
        } else {
          workersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder addWorkers(
          int index, AutoScalerRequest.PullResponse.WorkerStat.Builder builderForValue) {
        if (workersBuilder_ == null) {
          ensureWorkersIsMutable();
          workers_.add(index, builderForValue.build());
          onChanged();
        } else {
          workersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder addAllWorkers(
          java.lang.Iterable<? extends AutoScalerRequest.PullResponse.WorkerStat> values) {
        if (workersBuilder_ == null) {
          ensureWorkersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, workers_);
          onChanged();
        } else {
          workersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder clearWorkers() {
        if (workersBuilder_ == null) {
          workers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          workersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public Builder removeWorkers(int index) {
        if (workersBuilder_ == null) {
          ensureWorkersIsMutable();
          workers_.remove(index);
          onChanged();
        } else {
          workersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public AutoScalerRequest.PullResponse.WorkerStat.Builder getWorkersBuilder(
          int index) {
        return getWorkersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public AutoScalerRequest.PullResponse.WorkerStatOrBuilder getWorkersOrBuilder(
          int index) {
        if (workersBuilder_ == null) {
          return workers_.get(index);  } else {
          return workersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public java.util.List<? extends AutoScalerRequest.PullResponse.WorkerStatOrBuilder> 
           getWorkersOrBuilderList() {
        if (workersBuilder_ != null) {
          return workersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(workers_);
        }
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public AutoScalerRequest.PullResponse.WorkerStat.Builder addWorkersBuilder() {
        return getWorkersFieldBuilder().addBuilder(
            AutoScalerRequest.PullResponse.WorkerStat.getDefaultInstance());
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public AutoScalerRequest.PullResponse.WorkerStat.Builder addWorkersBuilder(
          int index) {
        return getWorkersFieldBuilder().addBuilder(
            index, AutoScalerRequest.PullResponse.WorkerStat.getDefaultInstance());
      }
      /**
       * <code>repeated .PullResponse.WorkerStat workers = 1;</code>
       */
      public java.util.List<AutoScalerRequest.PullResponse.WorkerStat.Builder> 
           getWorkersBuilderList() {
        return getWorkersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          AutoScalerRequest.PullResponse.WorkerStat, AutoScalerRequest.PullResponse.WorkerStat.Builder, AutoScalerRequest.PullResponse.WorkerStatOrBuilder> 
          getWorkersFieldBuilder() {
        if (workersBuilder_ == null) {
          workersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              AutoScalerRequest.PullResponse.WorkerStat, AutoScalerRequest.PullResponse.WorkerStat.Builder, AutoScalerRequest.PullResponse.WorkerStatOrBuilder>(
                  workers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          workers_ = null;
        }
        return workersBuilder_;
      }

      private java.util.List<java.lang.Integer> toKillWorkers_ = java.util.Collections.emptyList();
      private void ensureToKillWorkersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          toKillWorkers_ = new java.util.ArrayList<java.lang.Integer>(toKillWorkers_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getToKillWorkersList() {
        return java.util.Collections.unmodifiableList(toKillWorkers_);
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public int getToKillWorkersCount() {
        return toKillWorkers_.size();
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public int getToKillWorkers(int index) {
        return toKillWorkers_.get(index);
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public Builder setToKillWorkers(
          int index, int value) {
        ensureToKillWorkersIsMutable();
        toKillWorkers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public Builder addToKillWorkers(int value) {
        ensureToKillWorkersIsMutable();
        toKillWorkers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public Builder addAllToKillWorkers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToKillWorkersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toKillWorkers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toKillWorkers = 2;</code>
       */
      public Builder clearToKillWorkers() {
        toKillWorkers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int useless_ ;
      /**
       * <code>required int32 useless = 3;</code>
       */
      public boolean hasUseless() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 useless = 3;</code>
       */
      public int getUseless() {
        return useless_;
      }
      /**
       * <code>required int32 useless = 3;</code>
       */
      public Builder setUseless(int value) {
        bitField0_ |= 0x00000004;
        useless_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 useless = 3;</code>
       */
      public Builder clearUseless() {
        bitField0_ = (bitField0_ & ~0x00000004);
        useless_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PullResponse)
    }

    static {
      defaultInstance = new PullResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PullResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PullRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PullResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullResponse_WorkerStat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PullResponse_WorkerStat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021pullrequest.proto\"Q\n\013PullRequest\022\030\n\020to" +
      "DisableWorkers\030\001 \003(\005\022\027\n\017toRebornWorkers\030" +
      "\002 \003(\005\022\017\n\007useless\030\003 \002(\005\"\217\001\n\014PullResponse\022" +
      ")\n\007workers\030\001 \003(\0132\030.PullResponse.WorkerSt" +
      "at\022\025\n\rtoKillWorkers\030\002 \003(\005\022\017\n\007useless\030\003 \002" +
      "(\005\032,\n\nWorkerStat\022\013\n\003tag\030\001 \002(\005\022\021\n\tqueueSi" +
      "ze\030\002 \002(\005B\023B\021AutoScalerRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PullRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PullRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PullRequest_descriptor,
        new java.lang.String[] { "ToDisableWorkers", "ToRebornWorkers", "Useless", });
    internal_static_PullResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PullResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PullResponse_descriptor,
        new java.lang.String[] { "Workers", "ToKillWorkers", "Useless", });
    internal_static_PullResponse_WorkerStat_descriptor =
      internal_static_PullResponse_descriptor.getNestedTypes().get(0);
    internal_static_PullResponse_WorkerStat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PullResponse_WorkerStat_descriptor,
        new java.lang.String[] { "Tag", "QueueSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
